services:
  network-viz:
    container_name: network-viz
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    # While the Dockerfile COPYs our files to home on build,
    # this let's us live-reload without rebuilds while running the debug server
    volumes:
      - .:/home
