version: "3"
services:
  network-viz:
    container_name: network-viz
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    # This is written on build normally, but
    # mounting the volumes allows the debug server
    # to detect local changes to files and automatically
    # reload
    volumes:
      - .:/home
